use hotelMS;
select * from login;
create table room(Room_Number varchar(20),Availability varchar(20),Cleaning_Status varchar(20),Price varchar(20),Room_type varchar(20));
select * from room;
create table employee(Emp_name varchar(20),Emp_age varchar(20),Gender varchar(20),Job varchar(20),Salary varchar(20),Contact_No varchar(20),Email_ID varchar(50),Adhaar_No varchar(20));
select * from employee;
create table driver(Driver_name varchar(20),Driver_age varchar(20),Driver_gender varchar(20),Car_company varchar(20),Car_name varchar(20),Availability varchar(20),Loaction varchar(20));
select * from driver;
create table login2(Username varchar(20),Password varchar(20));
select * from login2;
insert into login2 values('joshiyash','7102901');
create table Hotel_Department(Department varchar(80),Budget varchar(80));
insert into Hotel_Department values('Office','50000');
select * from Hotel_Department;
insert into Hotel_Department values('House Keeping','40000');
insert into Hotel_Department values('Food','80000');
insert into Hotel_Department values('Kitchen Staff','20000');
insert into Hotel_Department values('Security','60000');
create table customer(ID varchar(50),Name varchar(50), Number varchar(80),Gender varchar(20),Country varchar(50),Room_Number varchar(20),Check_in varchar(100),Deposit varchar(100) );
select * from customer;